### ISSUE TITLE
Service for S3 URL

### ISSUE THREAD

**Issue by urfusion** [AlecRust/protected-video#41]
Is there any service for AWS S3 files?

If I am leaving service empty it not render video.

Even if I pass service html5 and url of S3 it is not working

**Comment by AlecRust** [comment]
This plugin currently only supports YouTube and Vimeo embeds. But loading self hosted videos would be a nice feature.

Currently this plugin uses the "non progressively enhanced" Plyr embed method [documented here](https://github.com/sampotts/plyr?tab=readme-ov-file#youtube).

To support HTML5 i.e. an MP4 on an S3 bucket, the way this plugin renders Plyr players would need to change to [this](https://github.com/sampotts/plyr?tab=readme-ov-file#html5-video).

Note that this embed method would also be less "secure" in that the URL to the MP4 would be visible in page source, and through Dev Tools as with the current embed method.

For now I would recommend using [Plyr HTML5 approach](https://github.com/sampotts/plyr?tab=readme-ov-file#html5-video) directly, or better yet the [Vidstack HTML5 player](https://www.vidstack.io/docs/player/api/providers/video) which is the successor to Plyr and more customisable.

I will look to add this feature to Protected Video, but I can't give any guarantees or timeline. I'm also not sure yet if this will happen before or after migrating the plugin to Vidstack (Plyr is now deprecated).
