### ISSUE TITLE
Protected Video block issue

### ISSUE THREAD

**Issue by junraemon** [AlecRust/protected-video#43]
WordPress Version: 6.5
Plugin Version:  1.11.2

I use Vimeo and it has been working before. But now it seems the Protected Video block is not working now on the WordPress block editor. It shows the following message:

![image](https://github.com/AlecRust/protected-video/assets/10971750/4a6146b5-6b22-491a-97b1-e9e1b62f6c2f)

**Comment by AlecRust** [comment]
I'm not sure what could be causing that.

> But now it seems

After what change? A new version of the plugin?

Are you sure you have the Protected Video plugin installed? The error suggests it has somehow been disabled/removed.

**Comment by junraemon** [comment]
Hi, I did some further checks and it seems that it got some conflicting issues with the Oxygen Builder version 4.8.2 if the WordPress version is 6.5. It seems to work with that set up if the WordPress version is lower than 6.5

**Comment by junraemon** [comment]
Hi, it seems that this issue is related to this one https://github.com/soflyy/oxygen-bugs-and-features/issues/3525
I'll close this now and track the fixes from the above link.
