### ISSUE TITLE
Copy Link option now visible

### ISSUE THREAD

**Issue by 4w00g4** [AlecRust/protected-video#45]
Hi there, 

I'm using your plugin and I've noticed that there is a "Copy Link" option in the top right of the video - this even shows on your example site. You have to click on the video window for it to display.

![Screenshot 2024-09-05 at 14 41 57](https://github.com/user-attachments/assets/c6fa5b36-3510-4038-b16b-79624d5a8989)

This undermines the purpose of the plugin. 

Paul

**Comment by AlecRust** [comment]
Hi Paul. This is part of the YouTube player, I can't remove it. It should not be clickable though, this plugin covers it.

Please let me know if this is in fact clickable.
